name: diff
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - certifi==2025.8.3
    - charset-normalizer==3.4.3
    - contourpy==1.3.0
    - cycler==0.12.1
    - dgl==0.6.1
    - fonttools==4.59.0
    - googledrivedownloader==1.1.0
    - idna==3.10
    - importlib-resources==6.5.2
    - isodate==0.7.2
    - jinja2==3.1.6
    - joblib==1.5.1
    - kiwisolver==1.4.7
    - littleutils==0.2.4
    - markupsafe==3.0.2
    - matplotlib==3.9.4
    - mpmath==1.3.0
    - networkx==3.2.1
    - numpy==1.23.0
    - ogb==1.3.6
    - outdated==0.2.2
    - packaging==25.0
    - pandas==2.3.1
    - pillow==11.3.0
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - python-louvain==0.16
    - pytz==2025.2
    - pyyaml==6.0.2
    - rdflib==7.1.4
    - requests==2.32.4
    - scikit-learn==0.24.2
    - scipy==1.13.1
    - seaborn==0.11.2
    - six==1.17.0
    - sympy==1.11.1
    - threadpoolctl==3.6.0
    - torch==1.8.1+cu111
    - torch-cluster==1.5.9
    - torch-geometric==1.7.2
    - torch-scatter==2.0.7
    - torch-sparse==0.6.10
    - torch-spline-conv==1.2.1
    - torchaudio==0.8.1
    - torchmetrics==0.6.0
    - torchvision==0.9.1+cu111
    - tqdm==4.59.0
    - typing-extensions==4.14.1
    - tzdata==2025.2
    - urllib3==2.5.0
    - zipp==3.23.0
prefix: /root/miniconda3/envs/diff
